import { expect, test } from '@playwright/test'

test.use({ storageState: { cookies: [], origins: [] } })

test('registration selects grade, filters recommendations and remembers choice', async ({ page }) => {
  await page.goto('/dang-nhap')
  await page.getByRole('tab', { name: 'Đăng ký' }).click()
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('study-demo-123')
  await page.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('different-password')
  await page.getByRole('button', { name: 'Tạo tài khoản' }).click()
  await expect(page.getByRole('alert')).toContainText('chưa khớp')
  await page.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('study-demo-123')
  await page.getByRole('button', { name: 'Tạo tài khoản' }).click()
  await expect(page.getByRole('heading', { name: 'Bạn đang học lớp mấy?' })).toBeVisible()
  await page.getByRole('button', { name: 'Lớp 12', exact: true }).click()
  await page.getByRole('button', { name: 'Bắt đầu học lớp 12' }).click()
  await expect(page).toHaveURL(/\/home$/)
  await expect(page.locator('.dashboard-lesson')).toHaveCount(3)
  await expect(page.locator('.dashboard-lesson').first()).toContainText('SGK lớp 12')
  await expect(page.getByRole('button', { name: 'Tài khoản' })).toContainText('learner')
  await page.getByLabel('Đổi lớp đề xuất').selectOption('10')
  await expect(page.locator('.dashboard-lesson').first()).toContainText('SGK lớp 10')
  await page.reload()
  await expect(page.getByLabel('Đổi lớp đề xuất')).toHaveValue('10')
  await page.getByRole('button', { name: 'Tài khoản' }).click()
  await page.getByRole('link', { name: 'Đăng xuất' }).click()
  await page.goto('/dang-nhap')
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('study-demo-123')
  await page.locator('.login-form button[type=submit]').click()
  await expect(page).toHaveURL(/\/home$/)
  await expect(page.getByLabel('Đổi lớp đề xuất')).toHaveValue('10')
})

test('mobile grade selection has no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/dang-nhap')
  await page.getByRole('button', { name: /Học thử không cần tài khoản/ }).click()
  await expect(page.locator('.grade-options button')).toHaveCount(7)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: 'Bắt đầu học lớp 7' }).click()
  await expect(page.locator('.dashboard-lesson')).toHaveCount(3)
})
