import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('resume saves the section and reader preferences without awarding learning progress', async ({ page }) => {
  await page.goto('/home')
  await page.locator('.study-action-read').click()
  await expect(page.locator('.dataset-section')).not.toHaveCount(0)
  await page.getByRole('button', { name: 'Aa · Chữ lớn' }).click()
  await page.getByRole('button', { name: 'Chế độ tập trung' }).click()
  await expect(page.locator('.dataset-reader')).toHaveClass(/is-focused/)
  await page.getByText('Mục lục bài học', { exact: true }).click()
  await page.locator('.dataset-toc a').nth(1).click()
  await expect.poll(() => page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('xuyen-su-ky-journal-v1')!).reading).map((item: any) => item.section))).toContain(1)
  await page.keyboard.press('Escape')
  await expect(page.locator('.study-action-read')).toContainText('Đọc tiếp bài dang dở')
  await page.reload()
  await page.locator('.study-action-read').click()
  await expect(page.locator('.reader-position-bar')).toContainText('Mục 2/')
  await expect(page.getByRole('button', { name: 'Aa · Cỡ thường' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.dataset-reader')).toHaveClass(/is-focused/)
  const saved = await page.evaluate(() => ({
    journal: JSON.parse(localStorage.getItem('xuyen-su-ky-journal-v1')!),
    session: JSON.parse(localStorage.getItem('xuyen-su-ky-demo-v1')!)
  }))
  expect(saved.journal.events).toHaveLength(0)
  expect(saved.session.earnedXp).toBe(0)
})

test('read lessons leave recommendations; review, saved collections and notebook download work', async ({ page }) => {
  await page.goto('/home')
  await expect(page.locator('.dashboard-lesson')).toHaveCount(3)
  const firstTitle = await page.locator('.dashboard-lesson-copy strong').first().innerText()
  await page.locator('.dashboard-lesson').first().click()
  await page.getByRole('button', { name: 'Lưu bài', exact: true }).click()
  await page.getByRole('button', { name: 'Đánh dấu đã đọc' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cần đọc lại', exact: true }).click()
  await page.getByLabel('Sổ tay của bạn').fill('Ghi nhớ bằng lời của mình.')
  await page.keyboard.press('Escape')
  await expect(page.locator('.dashboard-lesson-copy strong').first()).not.toHaveText(firstTitle)
  await expect(page.locator('.study-action-review')).toContainText('1 bài lớp 7')
  await expect(page.getByRole('progressbar', { name: 'Mục tiêu học trên trang chủ' })).toHaveAttribute('aria-valuenow', '2')
  await page.locator('.study-action-review').click()
  await expect(page.locator('.dataset-card')).toHaveCount(1)
  await expect(page.locator('.dataset-card')).toContainText(firstTitle)
  await page.locator('.study-action-saved').click()
  await expect(page.getByRole('combobox', { name: 'Lọc lớp sách giáo khoa' })).toHaveValue('all')
  await expect(page.locator('.dataset-card')).toHaveCount(1)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Tải sổ tay', exact: true }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toMatch(/^so-tay-xuyen-su-ky-/)
  const contents = await readFile((await download.path())!, 'utf-8')
  expect(contents).toContain(firstTitle)
  expect(contents).toContain('Ghi nhớ bằng lời của mình.')
  await page.reload()
  await page.locator('.study-action-review').click()
  await expect(page.locator('.dataset-card')).toHaveCount(1)
})

test('mobile quick navigation, search shortcut and reading layout are usable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/home')
  await expect(page.getByRole('navigation', { name: 'Điều hướng nhanh' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('study-mobile.png'), fullPage: false })
  await page.locator('.study-plan').screenshot({ path: testInfo.outputPath('study-plan-mobile.png') })
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('searchbox', { name: 'Tìm sự kiện, nhân vật, thời kỳ' })).toBeFocused()
  await page.getByRole('navigation', { name: 'Điều hướng nhanh' }).getByRole('link', { name: 'Học tập', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Điều hướng nhanh' }).getByRole('link', { name: 'Học tập', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.locator('.library-open').first().click()
  await page.screenshot({ path: testInfo.outputPath('reader-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('.dataset-reader').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await expect(page.getByRole('button', { name: 'Đóng bài đọc' })).toBeVisible()
  await page.keyboard.press('Escape')
})

test('empty review collection stays empty and search cancels old results', async ({ page }) => {
  await page.goto('/home')
  await page.locator('.study-action-review').click()
  await expect(page.locator('.library-empty')).toBeVisible()
  await page.getByRole('button', { name: 'Xem tất cả bài học' }).click()
  await expect(page.locator('.dataset-card')).toHaveCount(6)
  let finishOld!: () => void
  const oldFinished = new Promise<void>(resolve => { finishOld = resolve })
  await page.route('**/api/search?q=old*', async route => {
    await new Promise(resolve => setTimeout(resolve, 600))
    await route.fulfill({ json: { items: [{ id: 'old', lessonId: 'LS7_B01', lessonTitle: 'OUTDATED', grade: 7, sectionTitle: 'Old' }], total: 1 } }).catch(() => {})
    finishOld()
  })
  const input = page.getByRole('searchbox', { name: 'Tìm sự kiện, nhân vật, thời kỳ' })
  const oldRequest = page.waitForRequest('**/api/search?q=old*')
  await input.fill('old'); await input.press('Enter'); await oldRequest
  await input.fill('Bạch Đằng'); await input.press('Enter')
  await oldFinished
  await expect(page.locator('.dashboard-search-results')).not.toContainText('OUTDATED')
  await expect(page.locator('.dashboard-search-results > button').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.dashboard-search-results')).toHaveCount(0)
})
